### ISSUE TITLE
https/SSL for spiral.wiki

### ISSUE THREAD

**Issue by quimgil** [Orain/ansible-playbook#328]
At some point https://espiral.org was working correctly in Orain's servers (Kudu knows how). Then we changed the domain to spiral.wiki, but https is not working yet.

This is not urgent. This issue is being created only not to forget about it.

**Comment by Southparkfan** [comment]
Closing this due to lack of response - if @quimgil is able to send to send the cert + private key to me, I'll add the SSL cert to spiral.wiki.

**Comment by quimgil** [comment]
Argh, sorry, I was so busy at that time. And now things have changed so much...

Anyway, the current (and unused) SSL cert is about to expire, and I wonder whether I should renew it or create a new one. Whatever makes easier the solution of https://spiral.wiki problems.
