### ISSUE TITLE
Allow local development through Vagrant

### ISSUE THREAD

**Issue by Kudu** [Orain/ansible-playbook#368]
I'm not too sure whether any of us sysadmins do any sort of rigorous testing before deploying something, which is really unfortunate and a bit unbecoming of our current scale. A nice solution, which shouldn't be terribly hard to implement, would be to create a Vagrantfile capable of mocking up all the different servers in our cluster. This would allow us to have a local development environment that actually mimics the live Orain infrastructure, and perhaps even have a cheap staging server for testing and sharing stuff.

**Comment by addshore** [comment]
Also closing / ignoring this for now, can reopen when we have time, but right now this is a {{wontfix}} type thing
