### ISSUE TITLE
Abuse Filter is messed up

### ISSUE THREAD

**Issue by Arcane21** [Orain/ansible-playbook#502]
Some trusted users on All The Tropes have reported getting these messages:

The text you wanted to save was blocked by the spamfilter.

This is probably caused by a link to a blacklisted external site.

This has happened when attempting to post youtube and wikipedia links, and it has apparently affected legitimate users on other wikis. I have attempted tweaking the abusefilters to no avail, so I'm not sure what the issue is.

My internet is kinda screwy right now, so I can't diagnose this further at the moment, will update this with more info if need be.

Below is a report from our users: 
https://allthetropes.orain.org/w/index.php?title=User_talk:GethN7&offset=20150115225454&lqt_mustshow=2254#Here_is_the_copy_pasted_verision._What_I_saw_had_bullet_points_to_the_left_of_the_indented_lines_.281_bullet_point_per_line.29._2254

**Comment by JohnFLewis** [comment]
http://meta.wikimedia.org/wiki/Spam_blacklist is causing the issue.
