### ISSUE TITLE
ReCaptcha

### ISSUE THREAD

**Issue by Kudu** [Orain/ansible-playbook#517]
[https://www.mediawiki.org/wiki/Extension:ReCaptcha](ReCaptcha extension)

**Comment by addshore** [comment]
This is probably blocked on fixing the private git repo to add a new recpatcha key

**Comment by Southparkfan** [comment]
I installed the wrong version... >_< If #524 gets fixed, setting up the new reCaptcha is easy too!

**Comment by Arcane21** [comment]
Well, this needs fixed ASAP, see here for more details:

http://allthetropes.wikia.com/wiki/Thread:279579

**Comment by damuniz** [comment]
disabled.

@southparkfan can you please investigate ASAP

-- 
Thank You,
Dusti Muniz

**Comment by Southparkfan** [comment]
User Login is totally broken now, and I don't know why.

**Comment by Southparkfan** [comment]
Well to fix above User Login issue, ConfirmEdit, ReCaptcha (own extension), ReCaptcha (ConfirmEdit extension), and QuestyCaptcha (ConfirmEdit) are now completely disabled. Needs to be fixed.

**Comment by addshore** [comment]
I will look at this now

**Comment by addshore** [comment]
As a note, QuestyCaptcha has been re-enabled in
https://github.com/Orain/ansible-playbook/compare/4cd99eff9608f4d3dc6bd3ba3a00573e6dbb84fa...7174d17f0cae8e5e6df1c97c3e5d6c7724a11ca1

**Comment by addshore** [comment]
Trying to load reCaptcha on extloadwiki only:
https://github.com/Orain/ansible-playbook/compare/7174d17f0cae8e5e6df1c97c3e5d6c7724a11ca1...2667b3cc913dd97a9e292a47a9120aa158f2e4a4

Getting issues with CSP, even though www.google.com is explicitly mentioned in the CSP for scripts I still get the following

 > Refused to load the script 'http://www.google.com/recaptcha/api/challenge?k=6LcC5AATAAAAAFW3aPQLu-jiRdVct5P9rqiTUMEd' because it violates the following Content Security Policy directive: "script-src 'self' piwik.orain.org login.orain.org static.orain.org bits.wikimedia.org www.google.com tools.wmflabs.org *.gstatic.com pagead2.googlesyndication.com 'unsafe-inline' 'unsafe-eval'".

**Comment by addshore** [comment]
Slightly more usefull error from firefox..

>[21:49:09.660] Content Security Policy: Directive script-src https://extload.orain.org:443 https://piwik.orain.org:443 https://login.orain.org:443 https://static.orain.org:443 https://bits.wikimedia.org:443 https://www.google.com:443 https://tools.wmflabs.org:443 https://*.gstatic.com:443 https://pagead2.googlesyndication.com:443 https://:443 https://:443 violated by http://www.google.com/recaptcha/api/challenge?k=6LcC5AATAAAAAFW3aPQLu-jiRdVct5P9rqiTUMEd

This implies that even though http / https is not specified in the CSP it is still expected to be the same as the request.

The reason the recaptcha extension / confirm edit is serving a https link is because out LB makes internal requests using http

The below attempts to fix this but still needs some debugging
https://github.com/Orain/ansible-playbook/commit/28cdeed6e4fe0d76c0025a819e8cf7a3c820d69a
https://github.com/Orain/ansible-playbook/commit/f72bb049b65645bfc865900066c866880bce52c9

**Comment by addshore** [comment]
Recaptcha is now working on extload, I'll tidy it up and deploy it everywhere

**Comment by addshore** [comment]
Enabled a test everywhere in http://git.io/vetB8
This has already been running on extload for a while now

**Comment by addshore** [comment]
ConfirmEdit version of ReCaptch now enabled everywhere in https://github.com/Orain/ansible-playbook/commit/3d58126a015146ddc61b6bd58fba5cb11815ec96

Waiting for https://phabricator.wikimedia.org/T84918 and thus https://gerrit.wikimedia.org/r/#/c/179793/ for the new google recaptcha
