### ISSUE TITLE
Non comfirmed account spamming continues despite filters.

### ISSUE THREAD

**Issue by Arcane21** [Orain/ansible-playbook#534]
http://drunkardswalkforums.yuku.com/topic/11069/master/1/?page=2#.VOoWtS7p-ao

More info here.

**Comment by Southparkfan** [comment]
The filters on Meta are not global (anymore), I don't know why but perhaps some other people here might now.

I've created a filter (https://poserdazfreebies.orain.org/wiki/Special:AbuseFilter/1) which should assist Robkelk in fighting spam on his wiki, so please notify Robkelk if you want.

**Comment by Arcane21** [comment]
kk, thanks.
