### ISSUE TITLE
remove me

### ISSUE THREAD

**Issue by TannerFilip** [Orain/ansible-playbook#542]
please remove my ssh key and access to servers.

**Comment by Southparkfan** [comment]
Removal of SSH access was already done in 826cdb7e1e267a347e78e0b268f488211395c5bb (and I removed your account on the servers manually), so I assume your access already has been removed completely.

**Comment by ZacharyDuBois** [comment]
He means his key.
https://github.com/Orain/ansible-playbook/blob/master/roles/base/files/ssh/keys/tanner.pub

**Comment by Southparkfan** [comment]
Done in d9cf0ae8e4515bc799166f4f5fd9698fd7d66468.

**Comment by Southparkfan** [comment]
All shoulf be done now, please re-open if not.
