### ISSUE TITLE
Fix PHP PEAR Mail errors

### ISSUE THREAD

**Issue by Southparkfan** [Orain/ansible-playbook#576]
[cefcfe14] /w/index.php?title=MediaWiki:Sidebar&action=submit Exception from line 268 of /srv/mediawiki/w/includes/mail/UserMailer.php: PEAR mail package is not installed
They prevent people from saving their edits. This is only happening on prod9 - so I'm afraid we have to take that server out of production until we can fix this.
Backtrace:

#0 /srv/mediawiki/w/includes/mail/EmailNotification.php(484): UserMailer::send(array, MailAddress, string, string, MailAddress)
#1 /srv/mediawiki/w/includes/mail/EmailNotification.php(440): EmailNotification->sendPersonalised(User)
#2 /srv/mediawiki/w/includes/mail/EmailNotification.php(255): EmailNotification->compose(User)
#3 /srv/mediawiki/w/includes/mail/EmailNotification.php(182): EmailNotification->actuallyNotifyOnPageChange(User, Title, string, string, integer, integer, array, string)
#4 /srv/mediawiki/w/includes/changes/RecentChange.php(332): EmailNotification->notifyOnPageChange(User, Title, string, string, integer, integer, string)
#5 /srv/mediawiki/w/includes/changes/RecentChange.php(553): RecentChange->save()
#6 /srv/mediawiki/w/includes/page/WikiPage.php(1906): RecentChange::notifyEdit(string, Title, boolean, User, string, integer, string, integer, string, integer, integer, integer, boolean)
#7 /srv/mediawiki/w/includes/page/Article.php(2006): WikiPage->doEditContent(WikitextContent, string, integer, boolean, User, string)
#8 /srv/mediawiki/w/includes/EditPage.php(1920): Article->__call(string, array)
#9 /srv/mediawiki/w/includes/EditPage.php(1292): EditPage->internalAttemptSave(array, boolean)
#10 /srv/mediawiki/w/includes/EditPage.php(528): EditPage->attemptSave()
#11 /srv/mediawiki/w/includes/actions/EditAction.php(56): EditPage->edit()
#12 /srv/mediawiki/w/includes/actions/SubmitAction.php(40): EditAction->show()
#13 /srv/mediawiki/w/includes/MediaWiki.php(414): SubmitAction->show()
#14 /srv/mediawiki/w/includes/MediaWiki.php(282): MediaWiki->performAction(Article, Title)
#15 /srv/mediawiki/w/includes/MediaWiki.php(584): MediaWiki->performRequest()
#16 /srv/mediawiki/w/includes/MediaWiki.php(435): MediaWiki->main()
#17 /srv/mediawiki/w/index.php(46): MediaWiki->run()
#18 {main}

**Comment by Southparkfan** [comment]
Uncommented the "include_path" line in /etc/php5/fpm/php.ini on prod9. Apparently that was already done on prod8, but never was an ansible task..

**Comment by Southparkfan** [comment]
Issue seems fixed; ansibilizing the fix is high priority now.

**Comment by addshore** [comment]
Good work!
