### ISSUE TITLE
prod9 cronjob ansible run failing

### ISSUE THREAD

**Issue by addshore** [Orain/ansible-playbook#582]
when running ansible it seems to run fine!

When cron runs it it fails (can be seen on nagios)

TASK: [hhvm | Add hhvm to boot] ***********************************************
failed: [prod9] => {"changed": false, "cmd": "update-rc.d hhvm defaults 98", "delta": "0:00:00.003610", "end": "2015-04-05 11:20:59.714800", "rc": 127, "start": "2015-04-05 11:20:59.711190", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 1: update-rc.d: not found

FATAL: all hosts have already failed -- aborting

**Comment by Southparkfan** [comment]
Fixed.
