### ISSUE TITLE
Error while creating wiki

### ISSUE THREAD

**Issue by revi** [Orain/ansible-playbook#591]
When I tried to create wikis using [[[meta:Special:CreateWiki]]](https://meta.orain.org/wiki/Special:CreateWiki), I got the following error; Wiki was created while error was displayed.

    Unexpected non-MediaWiki exception encountered, of type "BadMethodCallException"

**Comment by Southparkfan** [comment]
That error is normal. I don't know how to solve the MWException, but you can ignore it.

**Comment by addshore** [comment]
Should this be reported to https://github.com/Orain/CreateWiki ?

**Comment by revi** [comment]
Hmm, I agree. Orain/CreateWiki#18. Closing this.
