### ISSUE TITLE
File:Lambert-van-den-Bos-Schauplatz-des-Krieges MG 9489.tif can not be shown

### ISSUE THREAD

**Issue by addshore** [Orain/ansible-playbook#592]
https://meta.orain.org/wiki/Stewards%27_noticeboard#Can_not_display_tif_image

https://meta.orain.org/wiki/File:Lambert-van-den-Bos-Schauplatz-des-Krieges_MG_9489.tif

"Error creating thumbnail: Invalid thumbnail parameters"

**Comment by Reception123** [comment]
@labster Please close. Works with "View Wikimedia commons"

**Comment by labster** [comment]
@Reception123 I can't close it, it's not my issue.

**Comment by addshore** [comment]
Works with "View Wikimedia commons"
