### ISSUE TITLE
HHVM 3.6 doesn't work

### ISSUE THREAD

**Issue by Southparkfan** [Orain/ansible-playbook#598]
After a forced HHVM upgrade yesterday (because HHVM 3.3.1 was removed from apt.wikimedia.org), Orain began 502'ing. I immediately suspected this was the result of a failed HHVM upgrade.

prod8 was not affected since HHVM was not restarted after the upgrade, but prod8 had weight 0 in HAProxy so it didn't serve traffic at all.

The nginx error log mostly consisted of this:
2015/05/24 12:35:20 [crit] 9602#0: *38356 connect() to unix:/var/run/hhvm/sock failed (13: Permission denied) while connecting to upstream, client: ::ffff:[REDACTED], server: *.orain.org, request:

I couldn't find a backup of HHVM actually, until I saw one in /var/cache/apt/archives at prod13-temp. I've transferred it to prod6:/var/www/ubuntu and my own VPS + installed it on prod9. After that HHVM worked again, and I've removed prod11 from the mediawiki backend.

@JohnFLewis, can you investigate why nginx is throwing these errors with HHVM 3.6?

**Comment by JohnFLewis** [comment]
Insufficient permissions on the sock.

**Comment by JohnFLewis** [comment]
HHVM 3.6.1 is now running live on all MW servers.
