### ISSUE TITLE
Recovering wikiconstitucio

### ISSUE THREAD

**Issue by quimgil** [Orain/ansible-playbook#607]
The change of DNS has impacted wikiconstitucio.orain.org. This URL doesn't render anything on a browser, because it redirects to http://wikiconstitucio.org/wiki/Portada, and wikiconstitucio.org is still pointing to Orain's DNS.

As a short term solution, it would be good to make http://wikiconstitucio.orain.org usable, even at the expense of ignoring the domain for now. With the website up again, their owners will think about the next steps.

**Comment by NDKilla** [comment]
If you'd like, I believe I can disable the use of the custom domain for now, but I believe @addshore has a way that you can change where your domain points so you can use it.

I believe feature requests are piling up right now and I'm hoping I don't break #605  before it gets merged

**Comment by NDKilla** [comment]
Oh. Addshore commented on your other issue already

**Comment by addshore** [comment]
wikiconstitucio.orain.org does now render
As for the custom domain the only current solution is documented at https://meta.orain.org/wiki/Tech:Custom_domains

**Comment by quimgil** [comment]
Let's say that rendering is good enough for now. If the owners of wikiconstituciowiki need anything else, I will report here. Thank you.
