### ISSUE TITLE
Connecting spiral.wiki domain with the wiki

### ISSUE THREAD

**Issue by quimgil** [Orain/ansible-playbook#608]
Yesterday I had to change the DNS of spiral.wiki in order to get my email working. Now we need to point the domain in the direction of the wiki. http://spiral.orain.org doesn't render because it points to the domain.

**Comment by NDKilla** [comment]
See my comment on #607

**Comment by quimgil** [comment]
It is still unclear to me what should I do to make http://spiral.wiki work.

**Comment by addshore** [comment]
spiral.orain.org does no render.
As for custom domains please see https://meta.orain.org/wiki/Tech:Custom_domains, this is currently the only working solution.

**Comment by quimgil** [comment]
Thanks. https://meta.orain.org/wiki/Tech:Custom_domains says:
> If Orain staff host the DNS for your domain on CloudFlare using the Orain account. Please ask us about this

OK, I'm interested.

**Comment by quimgil** [comment]
No need for this change now. Sorry for the noise.
