### ISSUE TITLE
A clear policy about own domains

### ISSUE THREAD

**Issue by quimgil** [Orain/ansible-playbook#609]
http://spiral.wiki and http://wikiconstitucio.org have suffered a lot of extra problems for being wikis hosted in Orain with own domain names (mainly DNS changes and the https problem). While I understand that own domains represent an additional layer of complexity, the service was offered, so we took it.
Orain should have a clear policy for supporting domains. Either you support them and then you take them into account when changing configurations etc, or you simply don't support them, and gives us a choice between accessing to our sites via *.orain.org or going to another services.
The current situation is ambiguous, and I don't think it benefits or makes happy anyone.

**Comment by addshore** [comment]
In my opinion we should support custom domains.
We should not host DNS server for custom domains.

Any domains should currently be CNAMED to lb.orain.org (our loadbalancer)
This way any infrastructure changes will not affect the domains as lb.orain.org will always point to our webservers.
The domains must then also currently be configured in our nginx config.

**Comment by NDKilla** [comment]
@addshore  for custom domains do they still have to be pointed to lb.orain.org? How do we set it up on our end? Feel free to email me.

**Comment by Reception123** [comment]
@NDKilla From what I know yes, they have to be pointed to lb.orain.org as permanenetfuturelab wiki is.

**Comment by addshore** [comment]
If you have access to our cloudflare account you can use permanenetfuturelab as an example.
Also re this ticket, I feel that currently our policy is very clear as specified at https://meta.orain.org/wiki/Tech:Custom_domains (although it is not ideal and we would like to do more) :/

**Comment by NDKilla** [comment]
Whenever I get back on cloudflare I'll be sure to look at the config for this wiki. Thanks @addshore
