### ISSUE TITLE
Numerous issues on All The Tropes

### ISSUE THREAD

**Issue by Arcane21** [Orain/ansible-playbook#614]
Page elements on multiple browsers have been loading poorly or not at all on ATT, causing problems with viewing and editing, as described best here:

http://drunkardswalkforums.yuku.com/reply/130299/All-The-Tropes-Wiki-Project-Part-V#reply-130299

I believe the cache of ATT's content on Orain/Cloudflare's end needs to be completely flushed to remedy the issue.

Addshore, a lot of this seems to the result of Cloudflare presenting badly outdated information via its caching, which is causing the issues. Being able to force their cache to update would obviate this concern.

**Comment by Southparkfan** [comment]
Purged the CloudFlare cache a few hours ago. Scribunto issues were confirmed, but now seem to be gone.
