### ISSUE TITLE
user cannot join on wiki

### ISSUE THREAD

**Issue by revi** [Orain/ansible-playbook#615]
User is reporting that they cannot join with error "sammelungwikiSammelungwiki" (original report in Korean at [here](http://gall.dcinside.com/board/view/?id=dcwiki&no=15174&page=1)).

I think the problem lies on [this](https://meta.orain.org/w/index.php?title=Database_list&diff=15887&oldid=15886).

**Comment by addshore** [comment]
Per your thoughts I have undone the edit that you linked to, please try again in 10 mins!

**Comment by revi** [comment]
13 mins since your comment, ```Unknown database 'SammelungwikiSammelungwiki' (10.131.158.209)```

**Comment by addshore** [comment]
Should be fixed by this
https://meta.orain.org/w/index.php?title=Database_list&diff=15917&oldid=15916

**Comment by NDKilla** [comment]
Apparently fudged up two different ways when adding that one to the list. Sorry guys hope this didn't cause any major issues
