### ISSUE TITLE
Allow uploads for registered users on ucdgsawiki

### ISSUE THREAD

**Issue by labster** [Orain/ansible-playbook#637]
Also, make sure they can upload pdf, doc, docx, xls, xlsx, ppt, pptx.

**Comment by labster** [comment]
Well, maybe I mean confirmed/autoconfirmed.  You know, users and not bots :)

**Comment by labster** [comment]
ping

**Comment by NDKilla** [comment]
Is there an open feature request on wiki? 

@wynter should look at this because yeah they could do it. Usually people only look at GitHub if they're adding the changes themselves.

**Comment by labster** [comment]
Yeah, sorry.  I no longer interact with the wiki, so I don't know how you handle issues now.

**Comment by addshore** [comment]
Well, as we have no link to a request / noone on this issue related to it I will close this for now....
