### ISSUE TITLE
Noticed numerous issues when running a MW database update

### ISSUE THREAD

**Issue by Arcane21** [Orain/ansible-playbook#691]
Some wikis have lots of Database error messages, and some seem to have severe issues with CentralNotice.

Rather hard to provide screenshots, but can be viewed easily while in shell by running a MW database update without the --quick option. Have your mouse poised on the scrollbar to pause and look over some of the issues when you see them, some wikis are spitting out hordes of database issues.

I suggest we force all jobs to update on all wikis, many wikis report uncommitted database writes.

**Comment by addshore** [comment]
Nice assigning....
Well, either these errors will all be logged, or send the output of the update to a file and grep for the errors.
Then lets fix them....
