### ISSUE TITLE
Repeated search results

### ISSUE THREAD

**Issue by addshore** [Orain/ansible-playbook#87]
Repeated search results seem to be growing over time, in any Orain wiki. See for instance https://wikiconstitucio.orain.org/w/index.php?search=pdf&title=Especial%3ACerca

As a side note, have you considered https://www.mediawiki.org/wiki/Extension:CirrusSearch ? This is the future-present for MediaWiki search, I have been testing it at mediawiki.org and ca.wikipedia.org, and I'd say it would be very good for Orain wikis (the remaining issues are more related with Wikimedia corners cases with templates, prefixes, exotic non-Latin scripts and stuff like that). The developers claim that the extension is simple to install. Fwiw I work with them and I'm sure they would be very supportive if you decide to give it a try.

PS: not sure where this bug belongs to. Filed here even if MediaWiki core itself doesn't seem to have this issue.

**Comment by Kudu** [comment]
Still an issue, at least on Orain Meta.

**Comment by Southparkfan** [comment]
Known issue, have no idea how to solve it except than trying to re-populate the searchindex table.

**Comment by Southparkfan** [comment]
Re-populated the searchindex table at metawiki, no luck. Needs investigation.

**Comment by Southparkfan** [comment]
@kudu I just fixed the issue. Do you still have problems with this, or can this be closed?

**Comment by addshore** [comment]
I believe this is {{resolved}}

**Comment by addshore** [comment]
https://phabricator.wikimedia.org/T64276

**Comment by addshore** [comment]
Now running across all wikis

**Comment by addshore** [comment]
Should now be fixed?

**Comment by addshore** [comment]
Fixed upstream for next release https://gerrit.wikimedia.org/r/186973
